project_id = "gkwzodsznrnbfafaqbtu"

[functions.listening-audio]
verify_jwt = false

[functions.listening-audio-admin]
verify_jwt = false

[functions.track-pageview]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false
